// File generated by FlutterFire CLI from google-services.json.
// This file is checked into git (no secrets — these are public client SDK values).

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions are not configured for web — '
        'please pass FirebaseOptions manually.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not configured for iOS — '
          'run flutterfire configure.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not configured for macOS — '
          'run flutterfire configure.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not configured for Windows — '
          'run flutterfire configure.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not configured for Linux — '
          'run flutterfire configure.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not configured for platform '
          '$defaultTargetPlatform — run flutterfire configure.',
        );
    }
  }

  /// Android config — values from google-services.json
  /// (project_id: zorkvdo, mobilesdk_app_id: 1:538884582505:android:8346726273bcafc0fe86f8)
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTIskiP89wQeEF9vmEzbgRgIH8MhE3v9c',
    appId: '1:538884582505:android:8346726273bcafc0fe86f8',
    messagingSenderId: '538884582505',
    projectId: 'zorkvdo',
    storageBucket: 'zorkvdo.firebasestorage.app',
  );
}
