"""Deterministic mock provider for dev/tests.

Returns canned responses keyed off the user prompt so tests can assert
without an API key. The mock still produces useful text for blueprint
generation when no real provider is configured.
"""
from __future__ import annotations

import hashlib
import json
from typing import Any

from ..types import AiMessage, AiResponse


class MockProvider:
    name = "mock"
    default_model = "mock-1"

    def __init__(self, default_model: str = "mock-1") -> None:
        self.default_model = default_model

    async def chat(
        self,
        *,
        messages: list[AiMessage],
        model: str,
        temperature: float = 0.7,
        max_tokens: int | None = None,
        tools: list[dict[str, Any]] | None = None,
    ) -> AiResponse:
        last_user = next((m for m in reversed(messages) if m.role == "user"), None)
        prompt = last_user.content if last_user else ""
        digest = hashlib.sha1(prompt.encode()).hexdigest()[:8]

        # Heuristic: if the prompt asks for JSON, return JSON.
        if "json" in prompt.lower() or "blueprint" in prompt.lower():
            text = json.dumps(
                {
                    "mock": True,
                    "digest": digest,
                    "summary": "Mock blueprint generated.",
                    "pace": "medium",
                    "tags": ["mock", "test"],
                    "notes": "Generated by MockProvider; configure AI_PROVIDER to enable real generation.",
                },
                indent=2,
            )
        else:
            text = f"[mock:{digest}] {prompt[:200]}"

        return AiResponse(
            text=text,
            model=model,
            usage={
                "prompt_tokens": max(1, len(prompt) // 4),
                "completion_tokens": max(1, len(text) // 4),
            },
            raw={"provider": "mock", "digest": digest},
        )

    async def embed(self, texts: list[str]) -> list[list[float]]:
        out: list[list[float]] = []
        for t in texts:
            h = hashlib.sha256(t.encode()).digest()
            # 8-dim float vector derived deterministically from text
            out.append([(b - 128) / 128.0 for b in h[:8]])
        return out
